Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.define "zabbix-server" do |host|
    host.vm.network "private_network", ip: "172.16.84.10"
    host.vm.synced_folder "../../", "/data"
    host.vm.hostname = "zabbix-server"

    host.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    host.vm.provision "shell", inline: "/usr/bin/env ZABBIX_REGISTRATION_TOKEN=qwerty123 /data/zabbix_server.sh"
  end

  config.vm.define "zabbix-agent" do |host|
    host.vm.network "private_network", ip: "172.16.84.11"
    host.vm.synced_folder "../../", "/data"
    host.vm.hostname = "zabbix-agent-01"

    host.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    host.vm.provision "shell", inline: "/usr/bin/env ZABBIX_REGISTRATION_TOKEN=qwerty123 /data/zabbix_agent.sh"
  end

end
